CREATE TABLE IF NOT EXISTS roles (
  id INT PRIMARY KEY AUTO_INCREMENT,

  name VARCHAR(255) NOT NULL UNIQUE,

  created_at DATETIME NOT NULL DEFAULT (NOW()),
  updated_at DATETIME NOT NULL DEFAULT (NOW())
);

INSERT INTO roles (name) VALUES
('Super Admin');
